//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftKnacksProject.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.WishLinkComments = new HashSet<WishLinkComment>();
            this.GiftLinkComments = new HashSet<GiftLinkComment>();
            this.Comments1 = new HashSet<Comment>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ParentCommentId { get; set; }
        public long UserId { get; set; }
        public string Text { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual ICollection<WishLinkComment> WishLinkComments { get; set; }
        public virtual ICollection<GiftLinkComment> GiftLinkComments { get; set; }
        public virtual ICollection<Comment> Comments1 { get; set; }
        public virtual Comment Comment1 { get; set; }
        public virtual User User { get; set; }
    }
}
