//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftKnacksProject.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long Id { get; set; }
        public int ContactTypeId { get; set; }
        public long UserId { get; set; }
        public string Value { get; set; }
        public bool MainContact { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
