//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftKnacksProject.Api.EfDao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class giftKnacksConnectionString1 : DbContext
    {
        public giftKnacksConnectionString1()
            : base("name=giftKnacksConnectionString1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<GiftLinkComment> GiftLinkComments { get; set; }
        public virtual DbSet<Gift> Gifts { get; set; }
        public virtual DbSet<GiftWishStatus> GiftWishStatuses { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WishCategory> WishCategories { get; set; }
        public virtual DbSet<Wish> Wishes { get; set; }
        public virtual DbSet<WishGiftLink> WishGiftLinks { get; set; }
        public virtual DbSet<WishLinkComment> WishLinkComments { get; set; }
        public virtual DbSet<OAuthClient> OAuthClients { get; set; }
    }
}
