//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftKnacksProject.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftWishStatus
    {
        public GiftWishStatus()
        {
            this.Gifts = new HashSet<Gift>();
            this.Wishes = new HashSet<Wish>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
        public int Code { get; set; }
    
        public virtual ICollection<Gift> Gifts { get; set; }
        public virtual ICollection<Wish> Wishes { get; set; }
    }
}
