//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftKnacksProject.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public Nullable<byte> Rate { get; set; }
        public Nullable<long> ReplyerId { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
