//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftKnacksProject.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishLinkComment
    {
        public long Id { get; set; }
        public long CommentId { get; set; }
        public long WishId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Wish Wish { get; set; }
    }
}
