//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftKnacksProject.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishCategory
    {
        public WishCategory()
        {
            this.WishCategories1 = new HashSet<WishCategory>();
            this.Wishes = new HashSet<Wish>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<WishCategory> WishCategories1 { get; set; }
        public virtual WishCategory WishCategory1 { get; set; }
        public virtual ICollection<Wish> Wishes { get; set; }
    }
}
