/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

INSERT INTO [Countries] ([Id], [Name]) VALUES ('AF', 'Afghanistan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AL', 'Albania');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('DZ', 'Algeria');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AS', 'American Samoa');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AD', 'Andorra');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AO', 'Angola');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AI', 'Anguilla');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AQ', 'Antarctica');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AR', 'Argentina');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AM', 'Armenia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AW', 'Aruba');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AU', 'Australia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AT', 'Austria');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AZ', 'Azerbaijan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BS', 'Bahamas');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BH', 'Bahrain');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BD', 'Bangladesh');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BB', 'Barbados');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BY', 'Belarus');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BE', 'Belgium');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BZ', 'Belize');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BJ', 'Benin');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BM', 'Bermuda');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BT', 'Bhutan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BO', 'Bolivia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BW', 'Botswana');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BV', 'Bouvet Island');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BR', 'Brazil');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BQ', 'British Antarctic Territory');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('VG', 'British Virgin Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BN', 'Brunei');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BG', 'Bulgaria');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BI', 'Burundi');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KH', 'Cambodia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CM', 'Cameroon');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CA', 'Canada');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CT', 'Canton and Enderbury Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CV', 'Cape Verde');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KY', 'Cayman Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CF', 'Central African Republic');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TD', 'Chad');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CL', 'Chile');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CN', 'China');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CX', 'Christmas Island');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CC', 'Cocos [Keeling] Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CO', 'Colombia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KM', 'Comoros');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CG', 'Congo - Brazzaville');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CD', 'Congo - Kinshasa');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CK', 'Cook Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CR', 'Costa Rica');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('HR', 'Croatia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CU', 'Cuba');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CY', 'Cyprus');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CZ', 'Czech Republic');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('DK', 'Denmark');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('DJ', 'Djibouti');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('DM', 'Dominica');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('DO', 'Dominican Republic');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NQ', 'Dronning Maud Land');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('DD', 'East Germany');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('EC', 'Ecuador');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('EG', 'Egypt');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SV', 'El Salvador');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('ER', 'Eritrea');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('EE', 'Estonia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('ET', 'Ethiopia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('FK', 'Falkland Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('FO', 'Faroe Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('FJ', 'Fiji');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('FI', 'Finland');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('FR', 'France');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GF', 'French Guiana');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PF', 'French Polynesia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TF', 'French Southern Territories');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('FQ', 'French Southern and Antarctic Territories');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GA', 'Gabon');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GM', 'Gambia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GE', 'Georgia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('DE', 'Germany');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GH', 'Ghana');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GI', 'Gibraltar');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GR', 'Greece');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GL', 'Greenland');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GD', 'Grenada');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GP', 'Guadeloupe');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GU', 'Guam');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GT', 'Guatemala');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GG', 'Guernsey');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GN', 'Guinea');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GY', 'Guyana');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('HT', 'Haiti');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('HN', 'Honduras');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('HK', 'Hong Kong SAR China');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('HU', 'Hungary');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('IS', 'Iceland');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('IN', 'India');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('Id', 'Indonesia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('IR', 'Iran');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('IQ', 'Iraq');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('IE', 'Ireland');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('IM', 'Isle of Man');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('IL', 'Israel');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('IT', 'Italy');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('JM', 'Jamaica');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('JP', 'Japan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('JE', 'Jersey');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('JT', 'Johnston Island');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('JO', 'Jordan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KZ', 'Kazakhstan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KE', 'Kenya');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KI', 'Kiribati');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KW', 'Kuwait');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LA', 'Laos');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LV', 'Latvia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LB', 'Lebanon');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LS', 'Lesotho');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LR', 'Liberia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LY', 'Libya');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LT', 'Lithuania');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LU', 'Luxembourg');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MO', 'Macau SAR China');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MK', 'Macedonia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MG', 'Madagascar');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MW', 'Malawi');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MY', 'Malaysia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MV', 'Maldives');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('ML', 'Mali');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MT', 'Malta');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MH', 'Marshall Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MQ', 'Martinique');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MR', 'Mauritania');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MU', 'Mauritius');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('YT', 'Mayotte');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('FX', 'Metropolitan France');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MX', 'Mexico');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('FM', 'Micronesia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MI', 'MIdway Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MD', 'Moldova');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MC', 'Monaco');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MN', 'Mongolia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('ME', 'Montenegro');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MS', 'Montserrat');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MA', 'Morocco');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MZ', 'Mozambique');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MM', 'Myanmar [Burma]');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NA', 'Namibia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NR', 'Nauru');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NP', 'Nepal');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NL', 'Netherlands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NT', 'Neutral Zone');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NC', 'New Caledonia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NZ', 'New Zealand');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NI', 'Nicaragua');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NE', 'Niger');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NG', 'Nigeria');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NU', 'Niue');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NF', 'Norfolk Island');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KP', 'North Korea');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('VD', 'North Vietnam');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('NO', 'Norway');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('OM', 'Oman');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PC', 'Pacific Islands Trust Territory');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PK', 'Pakistan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PW', 'Palau');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PS', 'Palestinian Territories');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PA', 'Panama');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PZ', 'Panama Canal Zone');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PG', 'Papua New Guinea');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PY', 'Paraguay');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('YD', 'People''s Democratic Republic of Yemen');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PE', 'Peru');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PH', 'Philippines');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PN', 'Pitcairn Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PL', 'Poland');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PT', 'Portugal');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PR', 'Puerto Rico');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('QA', 'Qatar');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('RO', 'Romania');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('RU', 'Russia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('RW', 'Rwanda');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('RE', 'Réunion');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SH', 'Saint Helena');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LC', 'Saint Lucia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('MF', 'Saint Martin');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('WS', 'Samoa');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SM', 'San Marino');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SA', 'Saudi Arabia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SN', 'Senegal');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('RS', 'Serbia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CS', 'Serbia and Montenegro');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SC', 'Seychelles');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SG', 'Singapore');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SK', 'Slovakia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SI', 'Slovenia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SB', 'Solomon Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SO', 'Somalia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('ZA', 'South Africa');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('KR', 'South Korea');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('ES', 'Spain');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SD', 'Sudan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SR', 'SuriName');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SZ', 'Swaziland');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SE', 'Sweden');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('CH', 'Switzerland');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SY', 'Syria');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('ST', 'São Tomé and Príncipe');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TW', 'Taiwan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TJ', 'Tajikistan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TZ', 'Tanzania');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TH', 'Thailand');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TL', 'Timor-Leste');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TG', 'Togo');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TK', 'Tokelau');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TO', 'Tonga');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TT', 'TrinIdad and Tobago');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TN', 'Tunisia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TR', 'Turkey');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TM', 'Turkmenistan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('UM', 'U.S. Minor Outlying Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('PU', 'U.S. Miscellaneous Pacific Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('VI', 'U.S. Virgin Islands');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('UG', 'Uganda');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('UA', 'Ukraine');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('SU', 'Union of Soviet Socialist Republics');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AE', 'United Arab Emirates');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('GB', 'United Kingdom');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('US', 'United States');

INSERT INTO [Countries] ([Id], [Name]) VALUES ('UY', 'Uruguay');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('UZ', 'Uzbekistan');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('VA', 'Vatican City');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('VE', 'Venezuela');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('VN', 'Vietnam');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('WK', 'Wake Island');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('WF', 'Wallis and Futuna');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('EH', 'Western Sahara');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('YE', 'Yemen');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('ZM', 'Zambia');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('ZW', 'Zimbabwe');
INSERT INTO [Countries] ([Id], [Name]) VALUES ('AX', 'Åland Islands');